config/routes.rb
Rails.application.routes.draw do

  resources :photos do
    collection do
      post :check
    end
    member do
      get :download
      post :alert_photo_ready
    end
  end

  get 'home/index'

  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploaders :avatars, AvatarUploader
  serialize :avatars, JSON

  after_create :create_pass


  def create_pass
    begin
      p = "kadro" + SecureRandom.hex(2)
      self.pass = p # or whatever you chose like UUID tools
      self.save
      break
    end while self.class.exists?(:pass => p)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def check
  end

  def download

  end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  http_basic_authenticate_with name: "kadroadmin", password: "phototo2017" , except: [:check , :download]
  before_action :set_photo, only: [:show, :edit, :update, :destroy,:alert_photo_ready]


  def alert_photo_ready
      p = "سلام، #{@photo.first_name if @photo.first_name.present?} #{@photo.last_name if @photo.last_name.present?} عزیز، عکس های شما آماده شده است.، از آدرس زیر می تونید مشاهده و دانلود کنید :) \n http://phototo.kadro.co \n کد خصوصی شما: #{@photo.pass} \n تیم کادرو"
      res = send_sms(@photo.phone , p)
      @photo.alerted = true
      @photo.save
      redirect_to @photo , notice: "پیام ارسال شد"
  end

  def check
    if params[:pass].present?
      pass = params[:pass]
      if Photo.exists?(pass: pass)
        p = Photo.find_by_pass(pass)
        redirect_to download_photo_path(p.pass)
      else
        redirect_to root_path , :notice => "آخ، پیدا نشد، کد خصوصیت رو چک کن دوباره :)"
      end
    else
      redirect_to root_path , :notice => " کد خصوصیت رو وارد کن :)"
    end
  end

  def download
    @photo = Photo.find_by_pass(params[:id])
    @photo.view_times = @photo.view_times + 1
    @photo.save
  end


  # GET /photos
  # GET /photos.json
  def index
    # byebug
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show

  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_photo
    @photo = Photo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def photo_params
    params.require(:photo).permit(:first_name, :last_name, :published , :pass , :phone, :email , :number , { avatars: [] }  )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  require "uri"
	require 'net/http'

  def send_sms(to,message)
    # if Rails.env.production?
    pass = "smspanel810190501"
    # differentiate hamrAhe avval and others :
    paramz = {}
    reciept = to
    if reciept[0] == "0"
      reciept.slice(0)
    end
    isdn = '+98' + reciept.to_s
    # encoded = URI.encode("https://bulksms.vsms.net/eapi/submission/send_sms/2/2.0?username=amvaleh&password=bulksms810190501&message=#{message}&msisdn=#{isdn}")
    # result = Net::HTTP.post_form(URI.parse(encoded),paramz)
    #
    # if Rails.env.production?
      result = Net::HTTP.get(URI.parse(URI.encode("http://smspanel.Trez.ir/SendMessageWithUrl.ashx?Username=arcasimap&Password=#{pass}&PhoneNumber=9830008632000014&MessageBody=#{message}&RecNumber=#{to}&Smsclass=1")))
    # end

    # soon, sending notifs through telegram
    # telegram_result = send_telegram_msg(isdn,message)
    return result
    # end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/home/index.html.erb
<header>
    <div class="container">
        <div class="row">
            <div class="col-sm-7">
                <div class="header-content">
                    <div class="header-content-inner ">
                        <h1 class="farsi_font" style="text-algin:right">
                          کد خصوصی شما:
                        </h1>
                        <%= form_tag check_photos_path do %>
                        <%= text_field_tag  "pass" , "" , class: "form-control input" , placeholder: "KADRO***" %>
                        <br>
                        <button href="#download" class="btn btn-outline btn-xl page-scroll farsi_font" type="submit" style="background:none;">
                          دریافت عکس من
                        </butotn>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="col-sm-5">
                <div class="device-container">
                    <div class="device-mockup iphone6_plus portrait white">
                        <div class="device">
                            <div class="screen">
                                <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                                 <%= image_tag "poster.jpg" , class:"img-responsive" %>
                            </div>
                            <div class="button">
                                <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!--

<section id="download" class="download text-center bg-primary">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h2 class="section-heading farsi_font">
                  فوتوتو چیست؟
                  </h2>
                <p class="farsi_font">
                  به مدت ۲ هفته، روز های یک شنبه، سه شنبه و جمعه
                  در ایل کافه دور هم جمع شویم،
                  <br>
                  کادرو شما را به یک عکس پرتره مهمان می کند.
                </p>
            </div>
        </div>
    </div>
</section> -->

<section id="features" class="features"  style="background:black;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="section-heading">
                    <h2 class="farsi_font" style="color:white">
                      یک عکس مهمان ما باشید
                      </h2>
                    <p class="text-muted farsi_font">
                    </p>
                    <hr>
                </div>
            </div>
        </div>
        <div class="row">
          <!--
            <div class="col-md-4">
                <div class="device-container">
                    <div class="device-mockup iphone6_plus portrait white">
                        <div class="device">
                            <div class="screen">
                                 <%= image_tag "poster2.jpg", class:"img-responsive img-rounded"%> </div>
                            <div class="button">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
             -->
            <div class="col-md-12">
                <div class="container-fluid">
                    <div class="row">
                      <% Photo.all.where(:published=>true).each do |p| %>
                        <% p.avatars.each do |f| %>
                          <div class="col-md-4 col-xs-12">
                              <div class="feature-item">
                                  <%= image_tag f.url(:medium) , class: "img-responsive " %>
                              </div>
                          </div>
                          <% end %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="cta">
    <div class="cta-content">
        <div class="container">
            <h2 style="font-family:iranyekan-bold; color:#245eb5 ">عکاسی
              <br>
              برای
              <br>
              تو
            </h2>
            <a href="https://www.kadro.co" class="btn btn-outline btn-xl page-scroll farsi_font" style="color:#245eb5">
              بریم ببینیم!
            </a>
        </div>
    </div>
    <!-- <div class="overlay"></div> -->
</section>

<section id="contact" class="contact bg-primary">
    <div class="container ">
        <h2 class="farsi_font">
          ما
          <i class="fa fa-heart"></i>
          شما هستیم!
         </h2>
        <ul class="list-inline list-social">
            <li class=" ">
                <a href="https://twitter.com/kadro_co"><i class="fa fa-twitter"></i></a>
            </li>
            <li class=" ">
                <a href="https://www.linkedin.com/company-beta/13340028/"><i class="fa fa-linkedin"></i></a>
            </li>
            <li class=" ">
                <a href="https://instagram.com/kadro_co"><i class="fa fa-instagram"></i></a>
            </li>
            <li class=" ">
              <a href="https://www.facebook.com/kadro.co"><i class="fa fa-facebook"></i></a>
            </li>
        </ul>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="img/phototo.png">

    <title> Phototo | Kadro.co </title>

    <!-- Bootstrap Core CSS -->
    <!-- <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <!-- Plugin CSS -->
    <!-- <link rel="stylesheet" href="lib/font-awesome/css/font-awesome.min.css"> -->
    <!-- <link rel="stylesheet" href="lib/simple-line-icons/css/simple-line-icons.css"> -->
    <!-- <link rel="stylesheet" href="lib/device-mockups/device-mockups.min.css"> -->

    <!-- Theme CSS -->
    <!-- <link href="css/new-age.min.css" rel="stylesheet"> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="7b42f204-8085-4ee3-9914-cd556f3ba2a4";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

  </head>

  <body id="page-top">
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/"> #Phototo </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="https://www.instagram.com/kadro_co/"> @kadro </a>
                    </li>
                    <li>
                        <a class="page-scroll farsi_font" href="https://reserve.kadro.co"> رزرو عکاس </a>
                    </li>
                    <li>
                        <a class="page-scroll farsi_font" href="https://www.kadro.co/"> کادرو </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
            <% if notice %>
            <div class="alert alert-info">
              <p class="farsi_font">
                <%= notice %>
              </p>
            </div>
            <% end %>
        </div>
        <!-- /.container-fluid -->
    </nav>

    <%= yield %>

    <footer class="">
        <div class="container">
            <ul class="list-inline farsi_font">
                <li>
                    <a href="https://kadro.co/privacy/"> حریم خصوصی </a>
                </li>
                <li>
                    <a href="https://kadro.co/terms/"> قوانین </a>
                </li>
                <li>
                    <a href="https://kadro.co/faq/">  سوالات </a>
                </li>
                <li>
                  &copy;
                  حق همه محتوا برای کادرو محفوظ است.
                </li>
            </ul>
        </div>
    </footer>

    <!-- jQuery -->
    <!-- <script src="lib/jquery/jquery.min.js"></script> -->

    <!-- Bootstrap Core JavaScript -->
    <!-- <script src="lib/bootstrap/js/bootstrap.min.js"></script> -->

    <!-- Plugin JavaScript -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Theme JavaScript -->
    <!-- <script src="js/new-age.min.js"></script> -->


  </body>

</html>

app/views/photos/_form.html.erb
<%= form_for(photo) do |f| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "نام" %>
    <%= f.text_field :first_name ,class: "form-control text-center farsi_font" %>
  </div>

  <br>

  <div class="field">
    <%= f.label "نام خانوادگی" %>
    <%= f.text_field :last_name,class: "form-control text-center farsi_font" %>
  </div>
  <br>


  <div class="field">
    <%= f.label "شماره موبایل" %>
    <%= f.number_field :phone ,class: "form-control text-center farsi_font"%>
  </div>

  <br>

  <div class="field">
    <%= f.label "ایمیل" %>
    <%= f.email_field :email ,class: "form-control text-center farsi_font"%>
  </div>

  <br>

  <hr style="color: white;
    border-style: groove;
    border-color: white; max-width: 100% !important;">
  <h3>
    با تشکر از شما
  </h3>

  <hr style="color: white;
    border-style: groove;
    border-color: white; max-width: 100% !important;">

  <br>


  <div class="field">
    <%= f.label "photo number"%>
    <%= f.text_field :number ,class: "form-control text-center farsi_font", placeholder: "شماره عکس دوربین" %>
  </div>

  <br>

  <div class="field">
    <%= f.label "password" %>
    <%= f.text_field :pass ,class: "form-control text-center farsi_font" , placeholder: "چیزی وارد نکنید!" %>
  </div>

  <br>

  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatars, multiple: true ,class: "form-control text-center" %>
  </div>
  <br>


  <div class="field">
    <%= f.label :published %>
    <%= f.check_box :published , class: "form-control text-center"  %>
  </div>

  <br>
  <div class="actions">
    <%= f.submit "ثبت" , class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/photos/download.html.erb
<section id="contact" class="contact" style="background: black;">
  <div class="container">
    <div class="row">
      <div class="col-md-7 col-xs-12 col-md-offset-2">

        <h4 class="farsi_font" style="color:white;line-height: 40px; text-align: justify;">
          سلام
          <span style="color:#2B87F9"> <%= @photo.first_name %> <%= @photo.last_name %>  </span>
          عزیز،
          به کادرو خوش آمدید،
          امیدواریم از عکس هاتون لذت ببرید :)
        </h4>
        <h5 class="farsi_font" style="color: #39abc5;line-height: 40px; text-align: justify;">
          اگر عکس تون رو در شبکه های اجتماعی استفاده می کنید، خوشحال میشیم  از تگ
          @kadro_co
          برای معرفی ما به دوستان تون
          استفاده کنید.
          <br>
          تیم کادرو
        </h5>
      </div>
      <br>
      <div class="col-xs-8 col-xs-offset-2">
        <% @photo.avatars.each do |p| %>
        <hr style="color: white;
        border-style: groove;
        border-color: white; max-width: 100% !important;">
        <br>
        <div class="row">
          <div class=" text-center col-md-4 col-xs-12">
            <%=link_to p.url(:thumb) do %>
            <%= image_tag p.url(:thumb) , class: "img-responsive img-rounded middle" %>
            <% end %>
          </div>
          <div class=" text-center col-md-4 col-xs-12">
            <%=link_to p.url(:medium) do %>

            <%= image_tag p.url(:medium) , class: "img-responsive img-rounded middle" %>
            <% end %>
          </div>
          <div class=" text-center col-md-4 col-xs-12">
            <%= link_to "دانلود فایل اصلی" , p.url, download: "phototo_#{@photo.first_name}_portrait" , class: "btn btn-outline btn-xl page-scroll farsi_font middle" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section id="contact" class="contact" style="background:black;">
  <div class="container ">
    <ul class="list-inline list-social">
      <li class=" ">
        <a href="https://twitter.com/kadro_co"><i class="fa fa-twitter"></i></a>
      </li>
      <li class=" ">
        <a href="https://www.linkedin.com/company-beta/13340028/"><i class="fa fa-linkedin"></i></a>
      </li>
      <li class=" ">
        <a href="https://instagram.com/kadro_co"><i class="fa fa-instagram"></i></a>
      </li>
      <li class=" ">
        <a href="https://www.facebook.com/kadro.co"><i class="fa fa-facebook"></i></a>
      </li>
    </ul>
  </div>
</section>

app/views/photos/edit.html.erb
<section id="download" class="download text-center bg-primary">
  <div class="container">
    <div class="row">
      <h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

</div>
</div>
</section>

app/views/photos/index.html.erb
<section id="download" class="download text-center bg-primary">
  <div class="container">
    <div class="row">
      <p id="notice"><%= notice %></p>

      <h1>Photos</h1>
      <%= link_to 'New Photo', new_photo_path, class: "btn btn-primary btn-large" %>
      <br>
      <br>
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>First name</th>
              <th>Last name</th>
              <th>Phone</th>
              <th>Email</th>
              <th>published</th>
              <th>pass</th>
              <th>Avatar</th>
              <th>Number</th>
              <th>alerted</th>
              <th>view_times</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @photos.order("created_at desc").each do |photo| %>
            <tr>
              <td><%= photo.first_name %></td>
              <td><%= photo.last_name %></td>
              <td><%= photo.phone %></td>
              <td><%= photo.email %></td>
              <td><%= photo.published %></td>
              <td><%= photo.pass %></td>
              <td><%= photo.avatars.count %>
                <% photo.avatars.each do |p| %>
                <%= image_tag p.url(:thumb) %>
                <% end %>
              </td>
              <td><%= photo.number %></td>
              <td><%= photo.alerted %></td>
              <td><%= photo.view_times %></td>
              <td><%= link_to 'Show', photo %></td>
              <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
              <td class="hidden"><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <br>
      <%= link_to 'New Photo', new_photo_path, class: "btn btn-primary btn-large" %>
    </div>
  </div>
</section>

app/views/photos/new.html.erb
<section id="download" class="download text-center bg-primary">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h1>New Photo</h1>

        <%= render 'form', photo: @photo %>
        <br>
        <br>
        <br>
        <%= link_to 'Back', photos_path , class: "btn btn-block btn-info" %>
      </div>
    </div>
  </div>
</section>

app/views/photos/show.html.erb
<section id="download" class="download text-center bg-primary">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">

        <p id="notice"><%= notice %></p>

        <%= form_tag alert_photo_ready_photo_path do %>
          <%= submit_tag "اعلان عکس ها آماده است" , class: "btn btn-danger btn-large" %>
        <% end %>

        <br>
        <br>

        <p>
          <strong>First name:</strong>
          <%= @photo.first_name %>
        </p>

        <p>
          <strong>Last name:</strong>
          <%= @photo.last_name %>
        </p>

        <p>
          <strong>Phone:</strong>
          <%= @photo.phone %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @photo.email %>
        </p>

        <p>
          <strong>published:</strong>
          <%= @photo.published %>
        </p>

        <p>
          <strong>pass:</strong>
          <%= @photo.pass %>
        </p>

        <p>
          <strong>Number:</strong>
          <%= @photo.number %>
        </p>


        <p>
          <strong>Alerted:</strong>
          <%= @photo.alerted %>
        </p>

        <p>
          <strong>view_times:</strong>
          <%= @photo.view_times %>
        </p>



        <p>
          <strong>Avatar:</strong>
          <% @photo.avatars.each do |p| %>
          <div class="alert alert-info">
          <%= image_tag p.url(:thumb) %>
          <%= link_to "medium" , p.url(:medium),class: "btn btn-primary" %>
          <%= link_to "original" , p.url ,class: "btn btn-primary"%>
        </div>
          <% end %>
        </p>





        <%= link_to 'Edit', edit_photo_path(@photo) %> |
        <%= link_to 'Back', photos_path %>

      </div>
    </div>
  </div>
</section>